### PR TITLE
Sketch a travis config file.

### PR DESCRIPTION
**Pull request by danielballan**
This is sketch to get us started, based the Ubuntu install procedure.

Thanks @aryabhatt for help with this.

### CODE REVIEW

**Comment by danielballan** [comment]
Power-cycled to trigger Travis-CI.

**Comment by danielballan** [comment]
This is failing because the build does not locate the HDF5 installed by the system package manager, an issue we are tracking in #9. @n-log-n would you be able to take a pass at #9?

**Comment by danielballan** [comment]
Bump. :- D

**Comment by iamfaisalkhan** [comment]
@danielballan We have gathered some HDF5 with known result. I will add those to CI and fix the travis script.

**Comment by danielballan** [comment]
I was hoping that this could be fixed before it was merged. The CI is failing on this error: https://travis-ci.org/AdvancedPhotonSource/xpcs-eigen/builds/551823487#L451

**Comment by iamfaisalkhan** [comment]
@danielballan Thanks for the script. 

I have fixed the build in the master. The testing code is in a different branch. I will add the tests as well to .travis script once I merge that branch with the master.

**Comment by danielballan** [comment]
Sure thing. Thanks for the fixes in `master`. Did you know that, as a `Contributor` you can you push to any PR branch. So, for example, when I want to suggest changes to a PR, I can push to the PR branch and then we can review them together before merging.

**Comment by iamfaisalkhan** [comment]
Sounds good. We will follow this strategy onwards from now.

**Pull request merged**
